name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
        UPSTREAM_WORKSPACE: 'github:pal-robotics/play_motion#kinetic-devel'
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
